SYSTEM_PACKAGES=(
    htop
    btop
    wget
    curl
    vim
    stow
    zsh
    fzf
    openssh
)

DEV_PACKAGES=(
    nodejs
    npm
    go
    docker
    docker-compose
    neovim
    tmux
)

ARCH_DEV_PACKAGES=(
    github-cli
    python
    python-pip
    rust
)

DEB_DEV_PACKAGES=(
    gh
    python3
    python3-pip
    rustc
    cargo
)

DESKTOP_PACKAGES=(
    xdg-user-dirs
    brightnessctl
    wlogout
)

ARCH_DESKTOP_PACKAGES=(
    hyprland
    hyprpaper
    hyprpicker
    hyprshot
    hyprlock
    wayle
    xdg-desktop-portal-hyprland
)

DEB_DESKTOP_DEPENDENCIES_PACKAGES=(
    meson
    wget
    build-essential
    ninja-build
    cmake-extras
    cmake
    gettext
    gettext-base
    fontconfig
    libfontconfig-dev
    libffi-dev
    libxml2-dev
    libdrm-dev
    libxkbcommon-x11-dev
    libxkbregistry-dev
    libxkbcommon-dev
    libpixman-1-dev
    libudev-dev
    libseat-dev
    seatd
    libxcb-dri3-dev
    libegl-dev
    libgles2
    libegl1-mesa-dev
    glslang-tools
    libinput-bin
    libinput-dev
    libxcb-composite0-dev
    libavutil-dev
    libavcodec-dev
    libavformat-dev
    libxcb-ewmh2
    libxcb-ewmh-dev
    libxcb-present-dev
    libxcb-icccm4-dev
    libxcb-render-util0-dev
    libxcb-res0-dev
    libxcb-xinput-dev
    libtomlplusplus3
    libre2-dev
    xdg-desktop-portal-wlr
    jq
    grim
    slurp
    wl-clipboard
    libnotify-bin
    pkg-config
    libcairo2-dev
    libpango1.0-dev
    libgbm-dev
    libdrm-dev
    libgl1-mesa-dev
    libpam0g-dev
    libwayland-dev
    wayland-protocols
    libxkbcommon-dev
    glslang-dev
    libglslang-dev
    glslang-tools
    libhyprlang-dev
    libhyprcursor-dev
    libaquamarine-dev
    libvulkan-dev
    vulkan-utility-libraries-dev
    libpugixml-dev
    libpixman-1-dev
    libgbm-dev
    libdisplay-info-dev
    libiniparser-dev
    libjpeg-dev
    libwebp-dev
    libmagic-dev
    librsvg2-dev
    libpng-dev
    libxcursor-dev
    libeis-dev
    libmuparser-dev
    libcanberra-dev
    libx11-xcb-dev
    libsdbus-c++-dev
    libgtk-4-dev
    liblua5.4-dev
    libxcb-errors-dev
    libtomlplusplus-dev
    libgtk4-layer-shell-dev
    libfftw3-dev
    libpipewire-0.3-dev
    clang
    libclang-dev
    llvm-dev
    gcc-14
    g++-14
    libgtksourceview-5-dev
)

ADDITIONAL_PACKAGES=(
    ghostty
    rofi
    dolphin
    udiskie
)

ARCH_ADDITIONAL_PACKAGES=(
    brave-bin
    visual-studio-code-bin
    ttf-jetbrains-mono-nerd
    ttf-font-awesome
)

DEB_ADDITIONAL_PACKAGES=(
    brave-browser
    fonts-jetbrains-mono
    fonts-font-awesome
)
